server:
  port: 8082

spring:
  application:
    name: intersection-control
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/intersection
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minIdle: 10
      idle-timeout: 10000
      maximumPoolSize: 30